SET NAMES utf8mb4;

USE enterprise_scaffold;

CREATE TABLE IF NOT EXISTS datahub_metadata_table (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    data_source_id BIGINT NOT NULL COMMENT '数据源ID',
    data_source_name VARCHAR(100) NOT NULL COMMENT '数据源名称',
    schema_name VARCHAR(100) NOT NULL COMMENT '数据库名或Schema名',
    table_name VARCHAR(100) NOT NULL COMMENT '表名',
    table_comment VARCHAR(500) DEFAULT NULL COMMENT '表注释',
    table_type VARCHAR(50) NOT NULL COMMENT '表类型：TABLE表，VIEW视图',
    row_count BIGINT DEFAULT NULL COMMENT '表行数',
    collect_batch_no VARCHAR(64) NOT NULL COMMENT '采集批次号',
    collect_time DATETIME NOT NULL COMMENT '采集时间',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0正常，1异常',
    create_by VARCHAR(64) DEFAULT NULL COMMENT '创建人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by VARCHAR(64) DEFAULT NULL COMMENT '更新人',
    update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删除，1已删除',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (id),
    KEY idx_data_source_id (data_source_id),
    KEY idx_schema_table (schema_name, table_name),
    KEY idx_collect_batch_no (collect_batch_no),
    KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='数据治理-元数据表信息表';

CREATE TABLE IF NOT EXISTS datahub_metadata_column (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    table_id BIGINT NOT NULL COMMENT '元数据表ID',
    data_source_id BIGINT NOT NULL COMMENT '数据源ID',
    data_source_name VARCHAR(100) NOT NULL COMMENT '数据源名称',
    schema_name VARCHAR(100) NOT NULL COMMENT '数据库名或Schema名',
    table_name VARCHAR(100) NOT NULL COMMENT '表名',
    column_name VARCHAR(100) NOT NULL COMMENT '字段名',
    column_comment VARCHAR(500) DEFAULT NULL COMMENT '字段注释',
    column_type VARCHAR(100) DEFAULT NULL COMMENT '完整字段类型',
    data_type VARCHAR(100) DEFAULT NULL COMMENT '基础数据类型',
    column_length INT DEFAULT NULL COMMENT '字段长度',
    numeric_precision INT DEFAULT NULL COMMENT '数字精度',
    numeric_scale INT DEFAULT NULL COMMENT '小数位数',
    nullable_flag TINYINT NOT NULL DEFAULT 1 COMMENT '是否允许为空：0否，1是',
    primary_key_flag TINYINT NOT NULL DEFAULT 0 COMMENT '是否主键：0否，1是',
    column_default VARCHAR(500) DEFAULT NULL COMMENT '默认值',
    ordinal_position INT DEFAULT NULL COMMENT '字段顺序',
    collect_batch_no VARCHAR(64) NOT NULL COMMENT '采集批次号',
    collect_time DATETIME NOT NULL COMMENT '采集时间',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0正常，1异常',
    create_by VARCHAR(64) DEFAULT NULL COMMENT '创建人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by VARCHAR(64) DEFAULT NULL COMMENT '更新人',
    update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删除，1已删除',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (id),
    KEY idx_table_id (table_id),
    KEY idx_data_source_id (data_source_id),
    KEY idx_schema_table (schema_name, table_name),
    KEY idx_column_name (column_name),
    KEY idx_collect_batch_no (collect_batch_no),
    KEY idx_primary_key_flag (primary_key_flag),
    KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='数据治理-元数据字段信息表';

CREATE TABLE IF NOT EXISTS datahub_metadata_collect_log (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    collect_batch_no VARCHAR(64) NOT NULL COMMENT '采集批次号',
    data_source_id BIGINT NOT NULL COMMENT '数据源ID',
    data_source_name VARCHAR(100) NOT NULL COMMENT '数据源名称',
    collect_status TINYINT NOT NULL COMMENT '采集状态：0成功，1失败',
    table_total INT NOT NULL DEFAULT 0 COMMENT '采集表数量',
    column_total INT NOT NULL DEFAULT 0 COMMENT '采集字段数量',
    error_msg TEXT DEFAULT NULL COMMENT '失败原因',
    start_time DATETIME NOT NULL COMMENT '开始时间',
    end_time DATETIME DEFAULT NULL COMMENT '结束时间',
    cost_time BIGINT DEFAULT NULL COMMENT '耗时毫秒',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0正常，1异常',
    create_by VARCHAR(64) DEFAULT NULL COMMENT '创建人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by VARCHAR(64) DEFAULT NULL COMMENT '更新人',
    update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删除，1已删除',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (id),
    UNIQUE KEY uk_collect_batch_no (collect_batch_no),
    KEY idx_data_source_id (data_source_id),
    KEY idx_collect_status (collect_status),
    KEY idx_start_time (start_time),
    KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='数据治理-元数据采集日志表';
