SET NAMES utf8mb4;

USE enterprise_scaffold;

CREATE TABLE IF NOT EXISTS datahub_datasource (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    datasource_code VARCHAR(64) NOT NULL COMMENT '数据源编码',
    datasource_name VARCHAR(100) NOT NULL COMMENT '数据源名称',
    datasource_type VARCHAR(32) NOT NULL COMMENT '数据源类型：MYSQL、POSTGRESQL、ORACLE、SQLSERVER、API',
    jdbc_url VARCHAR(500) NOT NULL COMMENT 'JDBC连接地址',
    host VARCHAR(100) DEFAULT NULL COMMENT '主机地址',
    port INT DEFAULT NULL COMMENT '端口号',
    database_name VARCHAR(100) DEFAULT NULL COMMENT '数据库名或服务名',
    username VARCHAR(100) DEFAULT NULL COMMENT '用户名',
    password VARCHAR(255) DEFAULT NULL COMMENT '密码，学习阶段暂明文保存，生产环境应加密',
    owner_name VARCHAR(50) DEFAULT NULL COMMENT '负责人',
    env_type VARCHAR(32) DEFAULT 'DEV' COMMENT '环境类型：DEV、TEST、PROD',
    test_status TINYINT DEFAULT 0 COMMENT '最近连接测试状态：0未测试，1成功，2失败',
    last_test_time DATETIME DEFAULT NULL COMMENT '最近连接测试时间',
    status TINYINT DEFAULT 0 COMMENT '状态：0正常，1停用',
    create_by VARCHAR(64) DEFAULT NULL COMMENT '创建者',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by VARCHAR(64) DEFAULT NULL COMMENT '更新者',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除：0未删除，1已删除',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (id),
    UNIQUE KEY uk_datasource_code (datasource_code),
    KEY idx_datasource_type (datasource_type),
    KEY idx_host (host),
    KEY idx_database_name (database_name),
    KEY idx_env_type (env_type),
    KEY idx_test_status (test_status),
    KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='数据治理-数据源管理表';

INSERT INTO datahub_datasource (
    datasource_code,
    datasource_name,
    datasource_type,
    jdbc_url,
    host,
    port,
    database_name,
    username,
    password,
    owner_name,
    env_type,
    test_status,
    status,
    create_by,
    remark
) VALUES
(
    'DATAHUB-MYSQL-001',
    '企业主数据 MySQL 数据源',
    'MYSQL',
    'jdbc:mysql://localhost:3306/enterprise_scaffold?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true',
    'localhost',
    3306,
    'enterprise_scaffold',
    'root',
    '',
    '数据治理管理员',
    'DEV',
    0,
    0,
    'admin',
    'D4-02 初始化数据源：本地开发 MySQL'
),
(
    'DATAHUB-MYSQL-002',
    '政务共享交换 MySQL 数据源',
    'MYSQL',
    'jdbc:mysql://10.10.20.21:3306/gov_exchange?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true',
    '10.10.20.21',
    3306,
    'gov_exchange',
    'gov_reader',
    '',
    '政务数据负责人',
    'TEST',
    0,
    0,
    'admin',
    'D4-02 初始化数据源：政务共享交换测试库'
),
(
    'DATAHUB-MYSQL-003',
    '能源企业生产数据 MySQL 数据源',
    'MYSQL',
    'jdbc:mysql://10.10.30.31:3306/energy_prod?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true',
    '10.10.30.31',
    3306,
    'energy_prod',
    'energy_reader',
    '',
    '能源数据负责人',
    'PROD',
    0,
    0,
    'admin',
    'D4-02 初始化数据源：能源企业生产数据源'
)
ON DUPLICATE KEY UPDATE
    datasource_name = VALUES(datasource_name),
    datasource_type = VALUES(datasource_type),
    jdbc_url = VALUES(jdbc_url),
    host = VALUES(host),
    port = VALUES(port),
    database_name = VALUES(database_name),
    username = VALUES(username),
    owner_name = VALUES(owner_name),
    env_type = VALUES(env_type),
    status = VALUES(status),
    update_time = CURRENT_TIMESTAMP,
    remark = VALUES(remark);
