SET NAMES utf8mb4;

USE enterprise_scaffold;

CREATE TABLE IF NOT EXISTS datahub_api_publish (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    api_code VARCHAR(64) NOT NULL COMMENT 'API编码',
    api_name VARCHAR(100) NOT NULL COMMENT 'API名称',
    datasource_id BIGINT NULL COMMENT '数据源ID',
    datasource_code VARCHAR(64) NULL COMMENT '数据源编码',
    datasource_name VARCHAR(100) NULL COMMENT '数据源名称',
    table_id BIGINT NOT NULL COMMENT '元数据表ID',
    table_code VARCHAR(100) NULL COMMENT '表编码',
    table_name VARCHAR(100) NOT NULL COMMENT '表名',
    table_comment VARCHAR(255) NULL COMMENT '表说明',
    api_path VARCHAR(200) NOT NULL COMMENT 'API访问路径',
    request_method VARCHAR(20) NOT NULL DEFAULT 'GET' COMMENT '请求方式',
    publish_type VARCHAR(30) NOT NULL DEFAULT 'TABLE_PAGE' COMMENT '发布类型：TABLE_PAGE表分页API',
    online_status TINYINT NOT NULL DEFAULT 0 COMMENT '上线状态：0下线，1上线',
    auth_required TINYINT NOT NULL DEFAULT 1 COMMENT '是否需要认证：0否，1是',
    owner_name VARCHAR(64) NULL COMMENT '负责人',
    publish_time DATETIME NULL COMMENT '发布时间',
    last_online_time DATETIME NULL COMMENT '最近上线时间',
    last_offline_time DATETIME NULL COMMENT '最近下线时间',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0正常，1停用',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删除，1已删除',
    remark VARCHAR(500) NULL COMMENT '备注',
    PRIMARY KEY (id),
    UNIQUE KEY uk_api_code (api_code),
    UNIQUE KEY uk_api_path (api_path),
    KEY idx_datasource_id (datasource_id),
    KEY idx_table_id (table_id),
    KEY idx_api_name (api_name),
    KEY idx_online_status (online_status),
    KEY idx_status (status),
    KEY idx_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='数据治理-API共享发布表';

CREATE TABLE IF NOT EXISTS datahub_api_call_log (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    call_code VARCHAR(64) NOT NULL COMMENT '调用流水号',
    api_id BIGINT NOT NULL COMMENT 'API发布ID',
    api_code VARCHAR(64) NOT NULL COMMENT 'API编码',
    api_name VARCHAR(100) NOT NULL COMMENT 'API名称',
    request_path VARCHAR(200) NOT NULL COMMENT '请求路径',
    request_method VARCHAR(20) NOT NULL COMMENT '请求方式',
    caller_ip VARCHAR(64) NULL COMMENT '调用方IP',
    call_status TINYINT NOT NULL DEFAULT 0 COMMENT '调用状态：0成功，1失败',
    error_msg VARCHAR(500) NULL COMMENT '错误信息',
    cost_time BIGINT NULL COMMENT '耗时毫秒',
    call_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '调用时间',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0有效，1无效',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删除，1已删除',
    remark VARCHAR(500) NULL COMMENT '备注',
    PRIMARY KEY (id),
    UNIQUE KEY uk_call_code (call_code),
    KEY idx_api_id (api_id),
    KEY idx_api_code (api_code),
    KEY idx_call_status (call_status),
    KEY idx_call_time (call_time),
    KEY idx_status (status),
    KEY idx_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='数据治理-API调用日志表';
