SET NAMES utf8mb4;

USE enterprise_scaffold;

CREATE TABLE IF NOT EXISTS mine_work_order (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    work_order_code VARCHAR(64) NOT NULL COMMENT '工单编码',
    alarm_event_id BIGINT NOT NULL COMMENT '告警事件ID',
    event_code VARCHAR(64) DEFAULT NULL COMMENT '告警事件编码',
    alarm_level TINYINT DEFAULT NULL COMMENT '告警级别：1一般，2重要，3严重',
    work_order_title VARCHAR(200) NOT NULL COMMENT '工单标题',
    work_order_content VARCHAR(1000) DEFAULT NULL COMMENT '工单内容',
    device_id BIGINT DEFAULT NULL COMMENT '设备ID',
    sensor_id BIGINT DEFAULT NULL COMMENT '传感器ID',
    sensor_code VARCHAR(64) DEFAULT NULL COMMENT '传感器编码',
    sensor_name VARCHAR(100) DEFAULT NULL COMMENT '传感器名称',
    sensor_type VARCHAR(64) DEFAULT NULL COMMENT '传感器类型',
    area_name VARCHAR(100) DEFAULT NULL COMMENT '所属区域',
    location VARCHAR(200) DEFAULT NULL COMMENT '安装位置',
    order_status TINYINT NOT NULL DEFAULT 0 COMMENT '工单状态：0待处理，1处理中，2已处理，3已关闭',
    handler_user_id BIGINT DEFAULT NULL COMMENT '处理人ID',
    handler_username VARCHAR(64) DEFAULT NULL COMMENT '处理人用户名',
    handle_time DATETIME DEFAULT NULL COMMENT '处理时间',
    handle_result VARCHAR(1000) DEFAULT NULL COMMENT '处理结果',
    close_user_id BIGINT DEFAULT NULL COMMENT '关闭人ID',
    close_username VARCHAR(64) DEFAULT NULL COMMENT '关闭人用户名',
    close_time DATETIME DEFAULT NULL COMMENT '关闭时间',
    close_result VARCHAR(1000) DEFAULT NULL COMMENT '关闭结果',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0有效，1无效',
    create_by VARCHAR(64) DEFAULT NULL COMMENT '创建者',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by VARCHAR(64) DEFAULT NULL COMMENT '更新者',
    update_time DATETIME DEFAULT NULL COMMENT '更新时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删除，1已删除',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (id),
    UNIQUE KEY uk_work_order_code (work_order_code),
    UNIQUE KEY uk_alarm_event_id (alarm_event_id),
    KEY idx_event_code (event_code),
    KEY idx_sensor_code (sensor_code),
    KEY idx_sensor_type (sensor_type),
    KEY idx_area_name (area_name),
    KEY idx_alarm_level (alarm_level),
    KEY idx_order_status (order_status),
    KEY idx_status (status),
    KEY idx_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='智能矿山工单表';
