SET NAMES utf8mb4;

USE enterprise_scaffold;

CREATE TABLE IF NOT EXISTS mine_device (
                                           id BIGINT NOT NULL AUTO_INCREMENT COMMENT '设备ID',
                                           device_code VARCHAR(64) NOT NULL COMMENT '设备编码',
    device_name VARCHAR(100) NOT NULL COMMENT '设备名称',
    device_type VARCHAR(50) NOT NULL COMMENT '设备类型',
    area_name VARCHAR(100) DEFAULT NULL COMMENT '所属区域',
    location VARCHAR(200) DEFAULT NULL COMMENT '安装位置',
    manufacturer VARCHAR(100) DEFAULT NULL COMMENT '生产厂家',
    model VARCHAR(100) DEFAULT NULL COMMENT '设备型号',
    install_date DATE DEFAULT NULL COMMENT '安装日期',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0正常 1停用 2维修 3故障',
    last_maintenance_time DATETIME DEFAULT NULL COMMENT '最近维护时间',
    create_by VARCHAR(64) DEFAULT NULL COMMENT '创建者',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by VARCHAR(64) DEFAULT NULL COMMENT '更新者',
    update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删除 1已删除',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (id),
    UNIQUE KEY uk_device_code (device_code),
    KEY idx_device_type (device_type),
    KEY idx_area_name (area_name),
    KEY idx_status (status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='智能矿山设备台账表';

CREATE TABLE IF NOT EXISTS mine_sensor (
                                           id BIGINT NOT NULL AUTO_INCREMENT COMMENT '传感器ID',
                                           sensor_code VARCHAR(64) NOT NULL COMMENT '传感器编码',
    sensor_name VARCHAR(100) NOT NULL COMMENT '传感器名称',
    sensor_type VARCHAR(50) NOT NULL COMMENT '传感器类型',
    device_id BIGINT DEFAULT NULL COMMENT '关联设备ID',
    area_name VARCHAR(100) DEFAULT NULL COMMENT '所属区域',
    location VARCHAR(200) DEFAULT NULL COMMENT '安装位置',
    unit VARCHAR(20) DEFAULT NULL COMMENT '计量单位',
    min_value DECIMAL(12,4) DEFAULT NULL COMMENT '正常最小值',
    max_value DECIMAL(12,4) DEFAULT NULL COMMENT '正常最大值',
    alarm_threshold DECIMAL(12,4) DEFAULT NULL COMMENT '报警阈值',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0正常 1停用 2故障',
    last_report_time DATETIME DEFAULT NULL COMMENT '最近上报时间',
    create_by VARCHAR(64) DEFAULT NULL COMMENT '创建者',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by VARCHAR(64) DEFAULT NULL COMMENT '更新者',
    update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删除 1已删除',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (id),
    UNIQUE KEY uk_sensor_code (sensor_code),
    KEY idx_device_id (device_id),
    KEY idx_sensor_type (sensor_type),
    KEY idx_area_name (area_name),
    KEY idx_status (status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='智能矿山传感器台账表';

INSERT IGNORE INTO mine_device (
    device_code,
    device_name,
    device_type,
    area_name,
    location,
    manufacturer,
    model,
    install_date,
    status,
    last_maintenance_time,
    create_by,
    create_time,
    remark
) VALUES
(
    'DEV-FAN-001',
    '主通风机一号',
    'VENTILATION_FAN',
    '一采区',
    '一采区主通风硐室',
    '山西矿山装备厂',
    'FBD-2x55',
    '2024-03-01',
    0,
    '2026-06-01 09:00:00',
    'admin',
    NOW(),
    '用于一采区主通风'
),
(
    'DEV-PUMP-001',
    '中央水泵一号',
    'WATER_PUMP',
    '中央泵房',
    '中央泵房一号位',
    '太原泵业设备有限公司',
    'MD280-43x5',
    '2024-05-10',
    0,
    '2026-06-10 10:00:00',
    'admin',
    NOW(),
    '用于井下排水'
),
(
    'DEV-BELT-001',
    '主运输皮带一号',
    'BELT_CONVEYOR',
    '主运输巷',
    '主运输巷入口',
    '山西煤机装备有限公司',
    'DSJ100',
    '2024-07-15',
    2,
    '2026-06-15 14:00:00',
    'admin',
    NOW(),
    '当前处于计划检修状态'
);

INSERT IGNORE INTO mine_sensor (
    sensor_code,
    sensor_name,
    sensor_type,
    device_id,
    area_name,
    location,
    unit,
    min_value,
    max_value,
    alarm_threshold,
    status,
    last_report_time,
    create_by,
    create_time,
    remark
) VALUES
(
    'SEN-GAS-001',
    '一采区瓦斯传感器一号',
    'GAS',
    (SELECT id FROM mine_device WHERE device_code = 'DEV-FAN-001' LIMIT 1),
    '一采区',
    '一采区回风巷',
    '%',
    0.0000,
    1.0000,
    1.0000,
    0,
    '2026-06-27 10:00:00',
    'admin',
    NOW(),
    '瓦斯浓度监测'
),
(
    'SEN-TEMP-001',
    '中央泵房温度传感器一号',
    'TEMPERATURE',
    (SELECT id FROM mine_device WHERE device_code = 'DEV-PUMP-001' LIMIT 1),
    '中央泵房',
    '中央泵房一号水泵旁',
    '℃',
    0.0000,
    60.0000,
    60.0000,
    0,
    '2026-06-27 10:00:00',
    'admin',
    NOW(),
    '设备环境温度监测'
),
(
    'SEN-VIB-001',
    '主运输皮带振动传感器一号',
    'VIBRATION',
    (SELECT id FROM mine_device WHERE device_code = 'DEV-BELT-001' LIMIT 1),
    '主运输巷',
    '主运输皮带机头',
    'mm/s',
    0.0000,
    8.0000,
    8.0000,
    0,
    '2026-06-27 10:00:00',
    'admin',
    NOW(),
    '皮带机振动监测'
);