SET NAMES utf8mb4;

USE enterprise_scaffold;

CREATE TABLE IF NOT EXISTS mine_alarm_rule (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    rule_code VARCHAR(64) NOT NULL COMMENT '规则编码',
    rule_name VARCHAR(100) NOT NULL COMMENT '规则名称',
    sensor_type VARCHAR(64) NOT NULL COMMENT '传感器类型，例如 GAS、TEMPERATURE、VIBRATION',
    compare_operator VARCHAR(10) NOT NULL COMMENT '比较符号：GT大于，GE大于等于，LT小于，LE小于等于，EQ等于',
    threshold_value DECIMAL(18,4) NOT NULL COMMENT '规则阈值',
    alarm_level TINYINT NOT NULL DEFAULT 1 COMMENT '告警级别：1一般，2重要，3严重',
    alarm_title VARCHAR(100) NOT NULL COMMENT '告警标题',
    alarm_content VARCHAR(500) DEFAULT NULL COMMENT '告警内容模板',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0启用，1停用',
    create_by VARCHAR(64) DEFAULT '' COMMENT '创建者',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by VARCHAR(64) DEFAULT '' COMMENT '更新者',
    update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删除，1已删除',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (id),
    UNIQUE KEY uk_rule_code (rule_code),
    KEY idx_sensor_type (sensor_type),
    KEY idx_alarm_level (alarm_level),
    KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='智能矿山告警规则表';

CREATE TABLE IF NOT EXISTS mine_alarm_event (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    event_code VARCHAR(64) NOT NULL COMMENT '告警事件编码',
    rule_id BIGINT NOT NULL COMMENT '告警规则ID，逻辑关联 mine_alarm_rule.id',
    rule_code VARCHAR(64) NOT NULL COMMENT '告警规则编码',
    rule_name VARCHAR(100) NOT NULL COMMENT '告警规则名称',
    sensor_data_id BIGINT NOT NULL COMMENT '传感器数据ID，逻辑关联 mine_sensor_data.id',
    sensor_id BIGINT NOT NULL COMMENT '传感器ID，逻辑关联 mine_sensor.id',
    sensor_code VARCHAR(64) NOT NULL COMMENT '传感器编码',
    sensor_name VARCHAR(100) NOT NULL COMMENT '传感器名称',
    sensor_type VARCHAR(64) NOT NULL COMMENT '传感器类型',
    device_id BIGINT DEFAULT NULL COMMENT '所属设备ID，逻辑关联 mine_device.id',
    area_name VARCHAR(100) DEFAULT NULL COMMENT '所属区域',
    location VARCHAR(200) DEFAULT NULL COMMENT '安装位置',
    data_value DECIMAL(18,4) NOT NULL COMMENT '触发告警的采集值',
    threshold_value DECIMAL(18,4) NOT NULL COMMENT '触发告警的规则阈值',
    compare_operator VARCHAR(10) NOT NULL COMMENT '比较符号：GT大于，GE大于等于，LT小于，LE小于等于，EQ等于',
    alarm_level TINYINT NOT NULL DEFAULT 1 COMMENT '告警级别：1一般，2重要，3严重',
    alarm_title VARCHAR(100) NOT NULL COMMENT '告警标题',
    alarm_content VARCHAR(500) DEFAULT NULL COMMENT '告警内容',
    alarm_time DATETIME NOT NULL COMMENT '告警时间',
    handle_status TINYINT NOT NULL DEFAULT 0 COMMENT '处理状态：0未处理，1已确认，2已关闭',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0有效，1无效',
    create_by VARCHAR(64) DEFAULT '' COMMENT '创建者',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by VARCHAR(64) DEFAULT '' COMMENT '更新者',
    update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删除，1已删除',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (id),
    UNIQUE KEY uk_event_code (event_code),
    UNIQUE KEY uk_rule_data (rule_id, sensor_data_id),
    KEY idx_rule_id (rule_id),
    KEY idx_sensor_data_id (sensor_data_id),
    KEY idx_sensor_id (sensor_id),
    KEY idx_sensor_code (sensor_code),
    KEY idx_sensor_type (sensor_type),
    KEY idx_area_name (area_name),
    KEY idx_alarm_level (alarm_level),
    KEY idx_alarm_time (alarm_time),
    KEY idx_handle_status (handle_status),
    KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='智能矿山告警事件表';

INSERT INTO mine_alarm_rule (
    rule_code,
    rule_name,
    sensor_type,
    compare_operator,
    threshold_value,
    alarm_level,
    alarm_title,
    alarm_content,
    status,
    create_by,
    create_time,
    deleted,
    remark
) VALUES
(
    'ALM-RULE-GAS-001',
    '瓦斯浓度超限告警',
    'GAS',
    'GE',
    1.0000,
    3,
    '瓦斯浓度超限',
    '瓦斯传感器采集值达到或超过阈值，存在安全风险。',
    0,
    'system',
    NOW(),
    0,
    'M1-04 初始化告警规则'
),
(
    'ALM-RULE-TEMP-001',
    '温度过高告警',
    'TEMPERATURE',
    'GE',
    40.0000,
    2,
    '温度过高',
    '温度传感器采集值达到或超过阈值，请关注设备运行状态。',
    0,
    'system',
    NOW(),
    0,
    'M1-04 初始化告警规则'
),
(
    'ALM-RULE-VIB-001',
    '振动过高告警',
    'VIBRATION',
    'GE',
    8.0000,
    2,
    '设备振动过高',
    '振动传感器采集值达到或超过阈值，设备可能存在异常。',
    0,
    'system',
    NOW(),
    0,
    'M1-04 初始化告警规则'
)
ON DUPLICATE KEY UPDATE
    rule_name = VALUES(rule_name),
    sensor_type = VALUES(sensor_type),
    compare_operator = VALUES(compare_operator),
    threshold_value = VALUES(threshold_value),
    alarm_level = VALUES(alarm_level),
    alarm_title = VALUES(alarm_title),
    alarm_content = VALUES(alarm_content),
    status = VALUES(status),
    update_time = NOW();
