SET NAMES utf8mb4;

USE enterprise_scaffold;

CREATE TABLE IF NOT EXISTS mine_maintenance_task (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    task_code VARCHAR(64) NOT NULL COMMENT '维护任务编码',
    device_id BIGINT NOT NULL COMMENT '设备ID',
    device_code VARCHAR(64) DEFAULT NULL COMMENT '设备编码',
    device_name VARCHAR(100) DEFAULT NULL COMMENT '设备名称',
    device_type VARCHAR(64) DEFAULT NULL COMMENT '设备类型',
    area_name VARCHAR(100) DEFAULT NULL COMMENT '所属区域',
    location VARCHAR(200) DEFAULT NULL COMMENT '安装位置',
    health_score INT DEFAULT NULL COMMENT '生成任务时设备健康分',
    risk_level INT DEFAULT NULL COMMENT '风险等级：0健康，1关注，2风险，3高危',
    risk_level_name VARCHAR(32) DEFAULT NULL COMMENT '风险等级名称',
    task_title VARCHAR(200) NOT NULL COMMENT '任务标题',
    task_content VARCHAR(1000) DEFAULT NULL COMMENT '任务内容',
    task_type INT NOT NULL DEFAULT 1 COMMENT '任务类型：0例行维护，1预测性维护',
    task_source INT NOT NULL DEFAULT 1 COMMENT '任务来源：0手动创建，1设备健康评分',
    task_status INT NOT NULL DEFAULT 0 COMMENT '任务状态：0待安排，1待执行，2处理中，3已关闭',
    priority INT NOT NULL DEFAULT 1 COMMENT '优先级：0低，1中，2高，3紧急',
    plan_start_time DATETIME DEFAULT NULL COMMENT '计划开始时间',
    plan_end_time DATETIME DEFAULT NULL COMMENT '计划结束时间',
    maintainer_user_id BIGINT DEFAULT NULL COMMENT '维护人员用户ID',
    maintainer_username VARCHAR(64) DEFAULT NULL COMMENT '维护人员用户名',
    handle_time DATETIME DEFAULT NULL COMMENT '处理时间',
    handle_result VARCHAR(1000) DEFAULT NULL COMMENT '处理结果',
    close_time DATETIME DEFAULT NULL COMMENT '关闭时间',
    close_result VARCHAR(1000) DEFAULT NULL COMMENT '关闭结果',
    status INT NOT NULL DEFAULT 0 COMMENT '状态：0有效，1无效',
    create_by VARCHAR(64) DEFAULT NULL COMMENT '创建人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by VARCHAR(64) DEFAULT NULL COMMENT '更新人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删除，1已删除',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (id),
    UNIQUE KEY uk_task_code (task_code),
    KEY idx_device_id (device_id),
    KEY idx_device_code (device_code),
    KEY idx_device_type (device_type),
    KEY idx_area_name (area_name),
    KEY idx_risk_level (risk_level),
    KEY idx_task_status (task_status),
    KEY idx_priority (priority),
    KEY idx_status (status),
    KEY idx_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='智能矿山预测性维护任务表';
