SET NAMES utf8mb4;

USE enterprise_scaffold;

CREATE TABLE IF NOT EXISTS risk_rule (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    rule_code VARCHAR(64) NOT NULL COMMENT '规则编码',
    rule_name VARCHAR(100) NOT NULL COMMENT '规则名称',
    rule_type VARCHAR(32) NOT NULL COMMENT '规则类型：AMOUNT/FREQUENCY/LOCATION/DEVICE/TIME/BLACKLIST',
    condition_type VARCHAR(32) NOT NULL COMMENT '条件类型',
    compare_operator VARCHAR(32) NOT NULL COMMENT '比较操作符：GT/GTE/LT/LTE/EQ/CONTAINS/NIGHT',
    threshold_value DECIMAL(18, 2) DEFAULT NULL COMMENT '阈值',
    risk_level TINYINT NOT NULL DEFAULT 1 COMMENT '风险等级：1低风险，2中风险，3高风险',
    risk_score INT NOT NULL DEFAULT 0 COMMENT '风险分',
    rule_content VARCHAR(500) DEFAULT NULL COMMENT '规则内容',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0启用，1停用',
    create_by VARCHAR(64) DEFAULT 'system' COMMENT '创建人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by VARCHAR(64) DEFAULT NULL COMMENT '更新人',
    update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删除，1已删除',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (id),
    UNIQUE KEY uk_rule_code (rule_code),
    KEY idx_rule_type (rule_type),
    KEY idx_risk_level (risk_level),
    KEY idx_status (status),
    KEY idx_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='风控规则表';

CREATE TABLE IF NOT EXISTS risk_rule_hit (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    hit_code VARCHAR(64) NOT NULL COMMENT '命中编码',
    transaction_id BIGINT NOT NULL COMMENT '交易ID',
    transaction_no VARCHAR(64) NOT NULL COMMENT '交易流水号',
    account_no VARCHAR(64) NOT NULL COMMENT '账号',
    customer_id VARCHAR(64) NOT NULL COMMENT '客户ID',
    customer_name VARCHAR(100) NOT NULL COMMENT '客户姓名',
    rule_id BIGINT NOT NULL COMMENT '规则ID',
    rule_code VARCHAR(64) NOT NULL COMMENT '规则编码',
    rule_name VARCHAR(100) NOT NULL COMMENT '规则名称',
    rule_type VARCHAR(32) NOT NULL COMMENT '规则类型',
    hit_value VARCHAR(200) DEFAULT NULL COMMENT '命中值',
    threshold_value DECIMAL(18, 2) DEFAULT NULL COMMENT '命中阈值',
    risk_level TINYINT NOT NULL DEFAULT 1 COMMENT '风险等级：1低风险，2中风险，3高风险',
    risk_score INT NOT NULL DEFAULT 0 COMMENT '风险分',
    hit_time DATETIME NOT NULL COMMENT '命中时间',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0未处理，1已处理',
    create_by VARCHAR(64) DEFAULT 'system' COMMENT '创建人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by VARCHAR(64) DEFAULT NULL COMMENT '更新人',
    update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删除，1已删除',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (id),
    UNIQUE KEY uk_hit_code (hit_code),
    UNIQUE KEY uk_transaction_rule (transaction_id, rule_id),
    KEY idx_transaction_id (transaction_id),
    KEY idx_transaction_no (transaction_no),
    KEY idx_account_no (account_no),
    KEY idx_customer_id (customer_id),
    KEY idx_rule_id (rule_id),
    KEY idx_rule_code (rule_code),
    KEY idx_rule_type (rule_type),
    KEY idx_risk_level (risk_level),
    KEY idx_status (status),
    KEY idx_hit_time (hit_time),
    KEY idx_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='风控规则命中表';

INSERT INTO risk_rule (
    rule_code,
    rule_name,
    rule_type,
    condition_type,
    compare_operator,
    threshold_value,
    risk_level,
    risk_score,
    rule_content,
    status,
    create_by,
    remark
) VALUES
('RISK_AMOUNT_10000', '大额交易规则', 'AMOUNT', 'amount', 'GTE', 10000.00, 2, 30, '交易金额大于等于10000元', 0, 'system', 'R3-03 默认规则：大额交易'),
('RISK_FREQ_3_10MIN', '十分钟高频交易规则', 'FREQUENCY', 'account_no', 'GTE', 3.00, 3, 40, '同一账号10分钟内交易次数大于等于3次', 0, 'system', 'R3-03 默认规则：高频交易'),
('RISK_LOCATION_OVERSEA', '异地交易规则', 'LOCATION', 'location', 'CONTAINS', NULL, 3, 35, '境外,香港,澳门,港澳', 0, 'system', 'R3-03 默认规则：异地交易'),
('RISK_DEVICE_ABNORMAL', '异常设备规则', 'DEVICE', 'device_id', 'CONTAINS', NULL, 2, 25, 'UNKNOWN,ROOT,ROOTED,EMULATOR,VIRTUAL', 0, 'system', 'R3-03 默认规则：异常设备'),
('RISK_TIME_NIGHT', '夜间交易规则', 'TIME', 'transaction_time', 'NIGHT', 23.00, 1, 15, '23:00-06:00 夜间交易', 0, 'system', 'R3-03 默认规则：夜间交易'),
('RISK_BLACKLIST_CUSTOMER', '黑名单客户规则', 'BLACKLIST', 'customer_id/account_no', 'CONTAINS', NULL, 3, 60, 'CUST_BLACK_001,ACC_BLACK_001', 0, 'system', 'R3-03 默认规则：黑名单')
ON DUPLICATE KEY UPDATE
    rule_name = VALUES(rule_name),
    rule_type = VALUES(rule_type),
    condition_type = VALUES(condition_type),
    compare_operator = VALUES(compare_operator),
    threshold_value = VALUES(threshold_value),
    risk_level = VALUES(risk_level),
    risk_score = VALUES(risk_score),
    rule_content = VALUES(rule_content),
    status = VALUES(status),
    update_by = 'system',
    update_time = CURRENT_TIMESTAMP,
    remark = VALUES(remark);
