SET NAMES utf8mb4;

USE enterprise_scaffold;

CREATE TABLE IF NOT EXISTS risk_review_order (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    review_order_code VARCHAR(64) NOT NULL COMMENT '审核单编号',
    transaction_id BIGINT NOT NULL COMMENT '交易ID',
    transaction_no VARCHAR(64) NOT NULL COMMENT '交易流水号',
    account_no VARCHAR(64) DEFAULT NULL COMMENT '账户号',
    customer_id VARCHAR(64) DEFAULT NULL COMMENT '客户ID',
    customer_name VARCHAR(100) DEFAULT NULL COMMENT '客户姓名',
    merchant_id VARCHAR(64) DEFAULT NULL COMMENT '商户ID',
    merchant_name VARCHAR(128) DEFAULT NULL COMMENT '商户名称',
    transaction_type VARCHAR(32) DEFAULT NULL COMMENT '交易类型',
    channel VARCHAR(32) DEFAULT NULL COMMENT '交易渠道',
    amount DECIMAL(18,2) DEFAULT NULL COMMENT '交易金额',
    currency VARCHAR(16) DEFAULT 'CNY' COMMENT '币种',
    total_score INT NOT NULL DEFAULT 0 COMMENT '风险总分',
    risk_level TINYINT NOT NULL DEFAULT 1 COMMENT '风险等级：1低风险，2中风险，3高风险',
    risk_result VARCHAR(32) NOT NULL DEFAULT 'REVIEW' COMMENT '风险结果：PASS放行，REVIEW人工审核，REJECT拒绝',
    review_status TINYINT NOT NULL DEFAULT 0 COMMENT '审核状态：0待审核，1审核通过，2审核拒绝',
    reviewer_user_id BIGINT DEFAULT NULL COMMENT '审核人用户ID',
    reviewer_username VARCHAR(64) DEFAULT NULL COMMENT '审核人用户名',
    review_time DATETIME DEFAULT NULL COMMENT '审核时间',
    review_result VARCHAR(500) DEFAULT NULL COMMENT '审核意见',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0正常，1异常',
    create_by VARCHAR(64) DEFAULT NULL COMMENT '创建人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by VARCHAR(64) DEFAULT NULL COMMENT '更新人',
    update_time DATETIME DEFAULT NULL COMMENT '更新时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删除，1已删除',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (id),
    UNIQUE KEY uk_review_order_code (review_order_code),
    UNIQUE KEY uk_transaction_id (transaction_id),
    KEY idx_transaction_no (transaction_no),
    KEY idx_account_no (account_no),
    KEY idx_customer_id (customer_id),
    KEY idx_risk_level (risk_level),
    KEY idx_risk_result (risk_result),
    KEY idx_review_status (review_status),
    KEY idx_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='风险人工审核单表';
