SET NAMES utf8mb4;

USE enterprise_scaffold;

CREATE TABLE IF NOT EXISTS risk_transaction (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    transaction_no VARCHAR(64) NOT NULL COMMENT '交易流水号',
    account_no VARCHAR(64) NOT NULL COMMENT '账户号',
    customer_id BIGINT DEFAULT NULL COMMENT '客户ID',
    customer_name VARCHAR(100) DEFAULT NULL COMMENT '客户姓名',
    merchant_id VARCHAR(64) DEFAULT NULL COMMENT '商户ID',
    merchant_name VARCHAR(100) DEFAULT NULL COMMENT '商户名称',
    transaction_type VARCHAR(32) NOT NULL COMMENT '交易类型：PAYMENT支付，TRANSFER转账，WITHDRAW取现，CONSUME消费',
    channel VARCHAR(32) NOT NULL COMMENT '交易渠道：APP，WEB，ATM，POS',
    amount DECIMAL(18,2) NOT NULL COMMENT '交易金额',
    currency VARCHAR(16) NOT NULL DEFAULT 'CNY' COMMENT '币种',
    ip_addr VARCHAR(64) DEFAULT NULL COMMENT '交易IP',
    device_id VARCHAR(128) DEFAULT NULL COMMENT '设备ID',
    location VARCHAR(100) DEFAULT NULL COMMENT '交易地点',
    transaction_time DATETIME NOT NULL COMMENT '交易时间',
    transaction_status INT NOT NULL DEFAULT 0 COMMENT '交易状态：0成功，1失败，2处理中',
    risk_flag INT NOT NULL DEFAULT 0 COMMENT '风险标记：0未命中风险，1命中风险',
    status INT NOT NULL DEFAULT 0 COMMENT '状态：0正常，1异常',
    create_by VARCHAR(64) DEFAULT NULL COMMENT '创建人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by VARCHAR(64) DEFAULT NULL COMMENT '更新人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删除，1已删除',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (id),
    UNIQUE KEY uk_transaction_no (transaction_no),
    KEY idx_account_no (account_no),
    KEY idx_customer_id (customer_id),
    KEY idx_customer_name (customer_name),
    KEY idx_merchant_id (merchant_id),
    KEY idx_transaction_type (transaction_type),
    KEY idx_channel (channel),
    KEY idx_transaction_time (transaction_time),
    KEY idx_transaction_status (transaction_status),
    KEY idx_risk_flag (risk_flag),
    KEY idx_status (status),
    KEY idx_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='银行风控交易流水表';
