import request from '../request'

export interface PageResult<T> { pageNo: number; pageSize: number; total: number; pages: number; records: T[] }
export interface AiopsAlertRulePageQuery { pageNo?: number; pageSize?: number; ruleCode?: string; ruleName?: string; resourceType?: string; metricType?: string; alertLevel?: number; status?: number }
export interface AiopsAlertRulePageVO { id: number; ruleCode: string; ruleName: string; resourceType: string; metricType: string; compareOperator: string; thresholdValue: number; alertLevel: number; alertTitle: string; alertContent: string; status: number; createTime: string; remark?: string }
export interface AiopsAlertEventPageQuery { pageNo?: number; pageSize?: number; eventCode?: string; ruleCode?: string; resourceCode?: string; resourceName?: string; resourceType?: string; ipAddr?: string; metricCode?: string; metricType?: string; alertLevel?: number; handleStatus?: number; status?: number }
export interface AiopsAlertEventPageVO { id: number; eventCode: string; ruleId: number; ruleCode: string; ruleName: string; metricDataId: number; resourceId: number; resourceCode: string; resourceName: string; resourceType: string; ipAddr: string; metricCode: string; metricName: string; metricType: string; metricValue: number; thresholdValue: number; compareOperator: string; alertLevel: number; alertTitle: string; alertContent: string; alertTime: string; handleStatus: number; status: number; createTime: string; remark?: string }
export interface AiopsAlertGenerateRequest { metricDataId?: number; resourceType?: string; metricType?: string; limit?: number }
function unwrapApiResult<T>(response: any): T { const payload = response && response.data !== undefined ? response.data : response; if (payload && typeof payload === 'object' && 'code' in payload && 'data' in payload) { if (payload.code !== 0) throw new Error(payload.msg || '请求失败'); return payload.data as T } return payload as T }
export async function getAiopsAlertRulePageApi(params: AiopsAlertRulePageQuery): Promise<PageResult<AiopsAlertRulePageVO>> { const r = await request.get<any, PageResult<AiopsAlertRulePageVO>>('/api/aiops/alert-rules/page', { params }); return unwrapApiResult<PageResult<AiopsAlertRulePageVO>>(r) }
export async function getAiopsAlertEventPageApi(params: AiopsAlertEventPageQuery): Promise<PageResult<AiopsAlertEventPageVO>> { const r = await request.get<any, PageResult<AiopsAlertEventPageVO>>('/api/aiops/alert-events/page', { params }); return unwrapApiResult<PageResult<AiopsAlertEventPageVO>>(r) }
export async function generateAiopsAlertEventsApi(data: AiopsAlertGenerateRequest): Promise<AiopsAlertEventPageVO[]> { const r = await request.post<any, AiopsAlertEventPageVO[]>('/api/aiops/alert-events/generate', data); return unwrapApiResult<AiopsAlertEventPageVO[]>(r) }
