<template>
  <div class="page-container">
    <div class="page-header"><div><h2>AIOps 告警中心</h2><p>查看告警规则，按指标数据生成告警事件。</p></div><div class="header-actions"><el-button @click="goDashboard">返回首页</el-button><el-button type="primary" @click="openGenerateDialog">生成告警事件</el-button><el-button type="success" @click="reloadAll">刷新</el-button></div></div>
    <el-card class="section-card"><template #header><div class="card-header"><span>告警规则</span><el-button link type="primary" @click="resetRuleQuery">重置</el-button></div></template><div class="query-grid"><el-input v-model="ruleQuery.ruleCode" clearable placeholder="规则编码"/><el-input v-model="ruleQuery.ruleName" clearable placeholder="规则名称"/><el-select v-model="ruleQuery.resourceType" clearable placeholder="资源类型"><el-option label="服务器" value="SERVER"/><el-option label="数据库" value="DATABASE"/><el-option label="中间件" value="MIDDLEWARE"/><el-option label="网络设备" value="NETWORK"/></el-select><el-select v-model="ruleQuery.metricType" clearable placeholder="指标类型"><el-option label="CPU" value="CPU"/><el-option label="内存" value="MEMORY"/><el-option label="磁盘" value="DISK"/><el-option label="网络" value="NETWORK"/><el-option label="MySQL" value="MYSQL"/><el-option label="Redis" value="REDIS"/></el-select><el-select v-model="ruleQuery.alertLevel" clearable placeholder="告警级别"><el-option label="一般" :value="1"/><el-option label="重要" :value="2"/><el-option label="严重" :value="3"/></el-select><el-select v-model="ruleQuery.status" clearable placeholder="状态"><el-option label="启用" :value="0"/><el-option label="停用" :value="1"/></el-select><el-button type="primary" @click="loadAlertRules">查询</el-button></div><el-table v-loading="ruleLoading" :data="alertRules" border><el-table-column prop="ruleCode" label="规则编码" min-width="170"/><el-table-column prop="ruleName" label="规则名称" min-width="180"/><el-table-column prop="resourceType" label="资源类型" width="120"/><el-table-column prop="metricType" label="指标类型" width="100"/><el-table-column prop="compareOperator" label="比较符" width="90"/><el-table-column prop="thresholdValue" label="阈值" width="100"/><el-table-column label="级别" width="90"><template #default="{ row }"><el-tag :type="alertLevelTag(row.alertLevel)">{{ alertLevelName(row.alertLevel) }}</el-tag></template></el-table-column><el-table-column prop="alertTitle" label="告警标题" min-width="180"/></el-table><el-pagination v-model:current-page="ruleQuery.pageNo" v-model:page-size="ruleQuery.pageSize" class="pagination" background layout="total, sizes, prev, pager, next" :total="ruleTotal" :page-sizes="[10,20,50]" @current-change="loadAlertRules" @size-change="loadAlertRules"/></el-card>
    <el-card class="section-card"><template #header><div class="card-header"><span>告警事件</span><el-button link type="primary" @click="resetEventQuery">重置</el-button></div></template><div class="query-grid"><el-input v-model="eventQuery.eventCode" clearable placeholder="事件编码"/><el-input v-model="eventQuery.resourceCode" clearable placeholder="资源编码"/><el-input v-model="eventQuery.resourceName" clearable placeholder="资源名称"/><el-select v-model="eventQuery.metricType" clearable placeholder="指标类型"><el-option label="CPU" value="CPU"/><el-option label="内存" value="MEMORY"/><el-option label="磁盘" value="DISK"/><el-option label="网络" value="NETWORK"/><el-option label="MySQL" value="MYSQL"/><el-option label="Redis" value="REDIS"/></el-select><el-select v-model="eventQuery.alertLevel" clearable placeholder="告警级别"><el-option label="一般" :value="1"/><el-option label="重要" :value="2"/><el-option label="严重" :value="3"/></el-select><el-select v-model="eventQuery.handleStatus" clearable placeholder="处理状态"><el-option label="未处理" :value="0"/><el-option label="已派单" :value="1"/><el-option label="已关闭" :value="2"/></el-select><el-button type="primary" @click="loadAlertEvents">查询</el-button></div><el-table v-loading="eventLoading" :data="alertEvents" border><el-table-column prop="id" label="ID" width="80"/><el-table-column prop="eventCode" label="事件编码" min-width="180"/><el-table-column prop="resourceCode" label="资源编码" min-width="150"/><el-table-column prop="resourceName" label="资源名称" min-width="160"/><el-table-column prop="metricType" label="指标类型" width="100"/><el-table-column prop="metricValue" label="指标值" width="100"/><el-table-column prop="thresholdValue" label="阈值" width="100"/><el-table-column label="级别" width="90"><template #default="{ row }"><el-tag :type="alertLevelTag(row.alertLevel)">{{ alertLevelName(row.alertLevel) }}</el-tag></template></el-table-column><el-table-column label="状态" width="100"><template #default="{ row }"><el-tag :type="handleStatusTag(row.handleStatus)">{{ handleStatusName(row.handleStatus) }}</el-tag></template></el-table-column><el-table-column prop="alertTime" label="告警时间" min-width="180"/></el-table><el-pagination v-model:current-page="eventQuery.pageNo" v-model:page-size="eventQuery.pageSize" class="pagination" background layout="total, sizes, prev, pager, next" :total="eventTotal" :page-sizes="[10,20,50]" @current-change="loadAlertEvents" @size-change="loadAlertEvents"/></el-card>
    <el-dialog v-model="generateDialogVisible" title="生成告警事件" width="520px"><el-form label-width="120px"><el-form-item label="指标数据ID"><el-input-number v-model="generateForm.metricDataId" :min="1"/></el-form-item><el-form-item label="资源类型"><el-select v-model="generateForm.resourceType" clearable placeholder="可选"><el-option label="服务器" value="SERVER"/><el-option label="数据库" value="DATABASE"/><el-option label="中间件" value="MIDDLEWARE"/><el-option label="网络设备" value="NETWORK"/></el-select></el-form-item><el-form-item label="指标类型"><el-select v-model="generateForm.metricType" clearable placeholder="可选"><el-option label="CPU" value="CPU"/><el-option label="内存" value="MEMORY"/><el-option label="磁盘" value="DISK"/><el-option label="网络" value="NETWORK"/><el-option label="MySQL" value="MYSQL"/><el-option label="Redis" value="REDIS"/></el-select></el-form-item><el-form-item label="扫描条数"><el-input-number v-model="generateForm.limit" :min="1" :max="1000"/></el-form-item></el-form><template #footer><el-button @click="generateDialogVisible=false">取消</el-button><el-button type="primary" :loading="generateLoading" @click="handleGenerateAlerts">生成</el-button></template></el-dialog>
  </div>
</template>
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { generateAiopsAlertEventsApi, getAiopsAlertEventPageApi, getAiopsAlertRulePageApi, type AiopsAlertEventPageQuery, type AiopsAlertEventPageVO, type AiopsAlertGenerateRequest, type AiopsAlertRulePageQuery, type AiopsAlertRulePageVO } from '../../api/aiops/alert'
const router = useRouter(); const ruleLoading=ref(false); const eventLoading=ref(false); const generateLoading=ref(false); const generateDialogVisible=ref(false); const alertRules=ref<AiopsAlertRulePageVO[]>([]); const alertEvents=ref<AiopsAlertEventPageVO[]>([]); const ruleTotal=ref(0); const eventTotal=ref(0)
const ruleQuery=reactive<AiopsAlertRulePageQuery>({pageNo:1,pageSize:10}); const eventQuery=reactive<AiopsAlertEventPageQuery>({pageNo:1,pageSize:10}); const generateForm=reactive<AiopsAlertGenerateRequest>({limit:100})
function goDashboard(){router.push('/dashboard')} async function reloadAll(){await Promise.all([loadAlertRules(),loadAlertEvents()])}
async function loadAlertRules(){ruleLoading.value=true; try{const p=await getAiopsAlertRulePageApi(ruleQuery); alertRules.value=p.records||[]; ruleTotal.value=p.total||0}catch(e){console.error(e); ElMessage.error('AIOps 告警规则加载失败')}finally{ruleLoading.value=false}}
async function loadAlertEvents(){eventLoading.value=true; try{const p=await getAiopsAlertEventPageApi(eventQuery); alertEvents.value=p.records||[]; eventTotal.value=p.total||0}catch(e){console.error(e); ElMessage.error('AIOps 告警事件加载失败')}finally{eventLoading.value=false}}
function resetRuleQuery(){Object.assign(ruleQuery,{pageNo:1,pageSize:10,ruleCode:undefined,ruleName:undefined,resourceType:undefined,metricType:undefined,alertLevel:undefined,status:undefined}); loadAlertRules()}
function resetEventQuery(){Object.assign(eventQuery,{pageNo:1,pageSize:10,eventCode:undefined,ruleCode:undefined,resourceCode:undefined,resourceName:undefined,resourceType:undefined,ipAddr:undefined,metricCode:undefined,metricType:undefined,alertLevel:undefined,handleStatus:undefined,status:undefined}); loadAlertEvents()}
function openGenerateDialog(){Object.assign(generateForm,{metricDataId:undefined,resourceType:undefined,metricType:undefined,limit:100}); generateDialogVisible.value=true}
async function handleGenerateAlerts(){generateLoading.value=true; try{const arr=await generateAiopsAlertEventsApi(generateForm); ElMessage.success(`告警事件生成完成，本次新增 ${arr.length} 条`); generateDialogVisible.value=false; await loadAlertEvents()}catch(e){console.error(e); ElMessage.error('生成 AIOps 告警事件失败')}finally{generateLoading.value=false}}
function alertLevelName(v?:number){return v===3?'严重':v===2?'重要':v===1?'一般':'-'} function alertLevelTag(v?:number){return v===3?'danger':v===2?'warning':'info'} function handleStatusName(v?:number){return v===2?'已关闭':v===1?'已派单':v===0?'未处理':'-'} function handleStatusTag(v?:number){return v===2?'success':v===1?'warning':v===0?'danger':'info'}
onMounted(reloadAll)
</script>
<style scoped>.page-container{min-height:100vh;padding:24px;background:#f5f7fb}.page-header{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;margin-bottom:16px}.page-header h2{margin:0 0 8px;color:#1f2f3d}.page-header p{margin:0;color:#667085}.header-actions{display:flex;flex-wrap:wrap;gap:8px}.section-card{margin-bottom:16px}.card-header{display:flex;justify-content:space-between;align-items:center}.query-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:14px;align-items:center;margin-bottom:16px}.pagination{margin-top:16px;justify-content:flex-end}@media(max-width:768px){.page-header{flex-direction:column}.header-actions{width:100%}}</style>
