<template>
  <div class="page-container">
    <div class="page-header"><div><h2>AIOps 运维工单</h2><p>将 AIOps 告警事件转为运维工单，并完成处理、关闭闭环。</p></div><div class="header-actions"><el-button @click="goDashboard">返回首页</el-button><el-button type="primary" @click="openCreateDialog">告警转工单</el-button><el-button type="success" @click="loadWorkOrders">刷新</el-button></div></div>
    <el-card class="section-card"><template #header><div class="card-header"><span>工单查询</span><el-button link type="primary" @click="resetQuery">重置</el-button></div></template><div class="query-grid"><el-input v-model="query.workOrderCode" clearable placeholder="工单编码"/><el-input v-model="query.eventCode" clearable placeholder="事件编码"/><el-input v-model="query.resourceCode" clearable placeholder="资源编码"/><el-input v-model="query.resourceName" clearable placeholder="资源名称"/><el-select v-model="query.metricType" clearable placeholder="指标类型"><el-option label="CPU" value="CPU"/><el-option label="内存" value="MEMORY"/><el-option label="磁盘" value="DISK"/><el-option label="网络" value="NETWORK"/><el-option label="MySQL" value="MYSQL"/><el-option label="Redis" value="REDIS"/></el-select><el-select v-model="query.alertLevel" clearable placeholder="告警级别"><el-option label="一般" :value="1"/><el-option label="重要" :value="2"/><el-option label="严重" :value="3"/></el-select><el-select v-model="query.orderStatus" clearable placeholder="工单状态"><el-option label="待处理" :value="0"/><el-option label="处理中" :value="1"/><el-option label="已处理" :value="2"/><el-option label="已关闭" :value="3"/></el-select><el-button type="primary" @click="loadWorkOrders">查询</el-button></div>
    <el-table v-loading="loading" :data="workOrders" border><el-table-column prop="workOrderCode" label="工单编码" min-width="180"/><el-table-column prop="eventCode" label="事件编码" min-width="180"/><el-table-column prop="resourceCode" label="资源编码" min-width="150"/><el-table-column prop="resourceName" label="资源名称" min-width="160"/><el-table-column prop="metricType" label="指标类型" width="100"/><el-table-column label="告警级别" width="100"><template #default="{ row }"><el-tag :type="alertLevelTag(row.alertLevel)">{{ alertLevelName(row.alertLevel) }}</el-tag></template></el-table-column><el-table-column label="状态" width="100"><template #default="{ row }"><el-tag :type="orderStatusTag(row.orderStatus)">{{ orderStatusName(row.orderStatus) }}</el-tag></template></el-table-column><el-table-column prop="handlerUsername" label="处理人" min-width="110"/><el-table-column prop="handleTime" label="处理时间" min-width="180"/><el-table-column prop="closeUsername" label="关闭人" min-width="110"/><el-table-column prop="closeTime" label="关闭时间" min-width="180"/><el-table-column label="操作" fixed="right" width="180"><template #default="{ row }"><el-button size="small" type="primary" :disabled="row.orderStatus===3" @click="openHandleDialog(row)">处理</el-button><el-button size="small" type="success" :disabled="row.orderStatus===3" @click="openCloseDialog(row)">关闭</el-button></template></el-table-column></el-table><el-pagination v-model:current-page="query.pageNo" v-model:page-size="query.pageSize" class="pagination" background layout="total, sizes, prev, pager, next" :total="total" :page-sizes="[10,20,50]" @current-change="loadWorkOrders" @size-change="loadWorkOrders"/></el-card>
    <el-dialog v-model="createDialogVisible" title="告警转运维工单" width="520px"><el-form label-width="120px"><el-form-item label="告警事件ID" required><el-input-number v-model="createForm.alertEventId" :min="1"/></el-form-item><el-form-item label="备注"><el-input v-model="createForm.remark" type="textarea" :rows="3"/></el-form-item></el-form><template #footer><el-button @click="createDialogVisible=false">取消</el-button><el-button type="primary" :loading="submitLoading" @click="handleCreateWorkOrder">生成</el-button></template></el-dialog>
    <el-dialog v-model="handleDialogVisible" title="处理运维工单" width="560px"><el-form label-width="120px"><el-form-item label="工单编码"><el-input v-model="handleForm.workOrderCode" disabled/></el-form-item><el-form-item label="处理结果" required><el-input v-model="handleForm.handleResult" type="textarea" :rows="4"/></el-form-item><el-form-item label="备注"><el-input v-model="handleForm.remark" type="textarea" :rows="3"/></el-form-item></el-form><template #footer><el-button @click="handleDialogVisible=false">取消</el-button><el-button type="primary" :loading="submitLoading" @click="handleWorkOrder">提交处理</el-button></template></el-dialog>
    <el-dialog v-model="closeDialogVisible" title="关闭运维工单" width="560px"><el-form label-width="120px"><el-form-item label="工单编码"><el-input v-model="closeForm.workOrderCode" disabled/></el-form-item><el-form-item label="关闭结果" required><el-input v-model="closeForm.closeResult" type="textarea" :rows="4"/></el-form-item><el-form-item label="备注"><el-input v-model="closeForm.remark" type="textarea" :rows="3"/></el-form-item></el-form><template #footer><el-button @click="closeDialogVisible=false">取消</el-button><el-button type="success" :loading="submitLoading" @click="closeWorkOrder">确认关闭</el-button></template></el-dialog>
  </div>
</template>
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { closeAiopsWorkOrderApi, createAiopsWorkOrderFromAlertApi, getAiopsWorkOrderPageApi, handleAiopsWorkOrderApi, type AiopsWorkOrderPageQuery, type AiopsWorkOrderPageVO } from '../../api/aiops/workOrder'
const router=useRouter(); const loading=ref(false); const submitLoading=ref(false); const total=ref(0); const workOrders=ref<AiopsWorkOrderPageVO[]>([]); const createDialogVisible=ref(false); const handleDialogVisible=ref(false); const closeDialogVisible=ref(false); const query=reactive<AiopsWorkOrderPageQuery>({pageNo:1,pageSize:10})
const createForm=reactive<{alertEventId?:number;remark:string}>({alertEventId:undefined,remark:''}); const handleForm=reactive({id:0,workOrderCode:'',handleResult:'',remark:''}); const closeForm=reactive({id:0,workOrderCode:'',closeResult:'',remark:''})
function goDashboard(){router.push('/dashboard')} async function loadWorkOrders(){loading.value=true; try{const p=await getAiopsWorkOrderPageApi(query); workOrders.value=p.records||[]; total.value=p.total||0}catch(e){console.error(e); ElMessage.error('AIOps 运维工单加载失败')}finally{loading.value=false}}
function resetQuery(){Object.assign(query,{pageNo:1,pageSize:10,workOrderCode:undefined,eventCode:undefined,alertLevel:undefined,resourceCode:undefined,resourceName:undefined,resourceType:undefined,ipAddr:undefined,metricType:undefined,orderStatus:undefined,status:undefined}); loadWorkOrders()}
function openCreateDialog(){createForm.alertEventId=undefined; createForm.remark='由 AIOps 告警事件生成运维工单'; createDialogVisible.value=true}
async function handleCreateWorkOrder(){if(!createForm.alertEventId){ElMessage.warning('请输入告警事件ID');return} submitLoading.value=true; try{const w=await createAiopsWorkOrderFromAlertApi({alertEventId:createForm.alertEventId,remark:createForm.remark}); ElMessage.success(`运维工单已生成：${w.workOrderCode||'已生成'}`); createDialogVisible.value=false; await loadWorkOrders()}catch(e){console.error(e); ElMessage.error('告警转运维工单失败')}finally{submitLoading.value=false}}
function openHandleDialog(row:AiopsWorkOrderPageVO){Object.assign(handleForm,{id:row.id,workOrderCode:row.workOrderCode,handleResult:'',remark:''}); handleDialogVisible.value=true}
async function handleWorkOrder(){if(!handleForm.handleResult.trim()){ElMessage.warning('请输入处理结果');return} submitLoading.value=true; try{const w=await handleAiopsWorkOrderApi(handleForm.id,{handleResult:handleForm.handleResult,remark:handleForm.remark}); ElMessage.success(`运维工单已处理：${w.workOrderCode||'已处理'}`); handleDialogVisible.value=false; await loadWorkOrders()}catch(e){console.error(e); ElMessage.error('处理运维工单失败')}finally{submitLoading.value=false}}
function openCloseDialog(row:AiopsWorkOrderPageVO){Object.assign(closeForm,{id:row.id,workOrderCode:row.workOrderCode,closeResult:'',remark:''}); closeDialogVisible.value=true}
async function closeWorkOrder(){if(!closeForm.closeResult.trim()){ElMessage.warning('请输入关闭结果');return} submitLoading.value=true; try{const w=await closeAiopsWorkOrderApi(closeForm.id,{closeResult:closeForm.closeResult,remark:closeForm.remark}); ElMessage.success(`运维工单已关闭：${w.workOrderCode||'已关闭'}`); closeDialogVisible.value=false; await loadWorkOrders()}catch(e){console.error(e); ElMessage.error('关闭运维工单失败')}finally{submitLoading.value=false}}
function alertLevelName(v?:number){return v===3?'严重':v===2?'重要':v===1?'一般':'-'} function alertLevelTag(v?:number){return v===3?'danger':v===2?'warning':'info'} function orderStatusName(v?:number){return v===3?'已关闭':v===2?'已处理':v===1?'处理中':v===0?'待处理':'-'} function orderStatusTag(v?:number){return v===3?'success':v===2?'primary':v===1?'warning':v===0?'danger':'info'}
onMounted(loadWorkOrders)
</script>
<style scoped>.page-container{min-height:100vh;padding:24px;background:#f5f7fb}.page-header{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;margin-bottom:16px}.page-header h2{margin:0 0 8px;color:#1f2f3d}.page-header p{margin:0;color:#667085}.header-actions{display:flex;flex-wrap:wrap;gap:8px}.section-card{margin-bottom:16px}.card-header{display:flex;justify-content:space-between;align-items:center}.query-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:14px;align-items:center;margin-bottom:16px}.pagination{margin-top:16px;justify-content:flex-end}@media(max-width:768px){.page-header{flex-direction:column}.header-actions{width:100%}}</style>
